export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_CURRENTLY_LOGGED = 'SAVE_CURRENTLY_LOGGED';
export const DELETE_CURRENTLY_LOGGED = 'DELETE_CURRENTLY_LOGGED';

export const GET_PREDMETI = 'GET_PREDMETI';
export const SAVE_PREDMETI = 'SAVE_PREDMETI';

export const GET_PREDMETI_STUDENT = 'GET_PREDMETI_STUDENT';
export const SAVE_PREDMETI_STUDENT = 'SAVE_PREDMETI_STUDENT';

export const GET_STUDENT_INFO = 'GET_STUDENT_INFO';
export const SAVE_STUDENT_INFO = 'SAVE_STUDENT_INFO';

export const GET_PROFESOR_INFO = 'GET_PROFESOR_INFO';
export const SAVE_PROFESOR_INFO = 'SAVE_PROFESOR_INFO';

export const PRIJAVA_ISPITA = 'PRIJAVA_ISPITA';
export const ODJAVA_ISPITA = 'ODJAVA_ISPITA';
export const GET_PRIJAVLJENI_ISPITI = 'GET_PRIJAVLJENI_ISPITI';

export const GET_ISPITI_ZA_OCENJIVANJE = 'GET_ISPITI_ZA_OCENJIVANJE';
export const SAVE_ISPITI_ZA_OCENJIVANJE = 'SAVE_ISPITI_ZA_OCENJIVANJE';

export const GET_STUDENTS_ZA_OCENJIVANJE = 'GET_STUDENTS_ZA_OCENJIVANJE';
export const SAVE_STUDENTS_ZA_OCENJIVANJE = 'SAVE_STUDENTS_ZA_OCENJIVANJE';

export const OCENA = 'OCENA';

export const GET_ISPITNI_ROKOVI = 'GET_ISPITNI_ROKOVI';
export const SAVE_ISPITNI_ROKOVI = 'SAVE_ISPITNI_ROKOVI';
export const ADD_ISPITNI_ROK = 'ADD_ISPITNI_ROK';