export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_CURRENTLY_LOGGED = 'SAVE_CURRENTLY_LOGGED';
export const DELETE_CURRENTLY_LOGGED = 'DELETE_CURRENTLY_LOGGED';

export const GET_PREDMETI = 'GET_PREDMETI';
export const SAVE_PREDMETI = 'SAVE_PREDMETI';

export const GET_PREDMETI_STUDENT = 'GET_PREDMETI_STUDENT';
export const SAVE_PREDMETI_STUDENT = 'SAVE_PREDMETI_STUDENT';

export const GET_STUDENT_INFO = 'GET_STUDENT_INFO';
export const SAVE_STUDENT_INFO = 'SAVE_STUDENT_INFO';

export const GET_PROFESOR_INFO = 'GET_PROFESOR_INFO';
export const SAVE_PROFESOR_INFO = 'SAVE_PROFESOR_INFO';